### ISSUE TITLE
Data provider

### ISSUE THREAD

**Issue by nicola** [densekernel/3001#2]
- [ ] Infrastructure: have a query-able API (in node? in python?) #3
  - [ ] where we can query raw data. #4
    - [ ] a database where to store data #5
    - [ ] a proxy api to get live data #6
- [ ] Which data do we want?
- [ ] Actual data: Have data stored
  - [x] evaluate DB to use (still #5)
  - [x] store TFL data for now #7

Assign yourself to some issues
