### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by nicola** [densekernel/3001#8]
This involved the following
- [x] find out what map we like (open street map? mapbox?) #9 
- [ ] choose a framework #10 make sure we follow the structure defined in #4 to retrieve data #11
- [ ] building strategy (tools to automate deployment)  #12
- [x] have a first example #13

**Comment by nicola** [comment]
@himerzi great, make sure you find people to start on these four points

**Comment by himerzi** [comment]
@nicola Aren't we just going to let people on the tech team join whichever sub-team interests them? (ie i'm not going out and telling people that their doing visualisation - right?)

**Comment by nicola** [comment]
@himerzi, well. It is up to you to define your role. You will be actively work in this team and report weekly what has been happening in this team (so by finding other people or wait until someone joins), you are basically taking the lead

**Comment by himerzi** [comment]
@nicola Yup!

**Comment by nicola** [comment]
Ha!

**Comment by ChristosD** [comment]
+1
